{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bioqc
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.5.2"

source:
  fn: bioqc_1.5.2.zip
  url:
    - https://github.com/Accio/BioQC/archive/master.zip

  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, knitr, rmarkdown, shiny
requirements:
  build:
    - r-devtools 1.13
    - r-rcpp 0.12.11
    - bioconductor-biobase 2.38
    - r-r.methodss3 1.7.1
    - r-testthat 1.0.2
    - r-base 3.4.1
    - r-roxygen2 6.0.1
    - libgcc 5.2.0  # [not osx]
    - libgcc 4.8.5  # [osx]
    - libiconv 1.15 # [osx]
    - glib 2.50.2
    - r-bindrcpp 0.2
    - posix               # [win]
    - {{native}}toolchain # [win]
    - gcc                 # [not win]

  run:
    - r-r.methodss3 >=1.7.1
    - bioconductor-biobase >=2.38
    - r-base >=3.0.2
    - r-roxygen2 >=6.0.1
    - r-rcpp >=0.12.3
    - libgcc

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('BioQC')" # [not win]
    - "\"%R%\" -e \"library('BioQC')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/Accio/BioQC
  license: GPL (>=3)
  summary: BioQC performs quality control of high-throughput expression data based on tissue gene signatures. It can detect tissue heterogeneity in gene expression data. The core algorithm is a Wilcoxon-Mann-Whitney test that is optimised for high performance.
  license_family: GPL
